(setf a (make-instance 'point))
(set-x a 4)
(set-y a 4)
(setf b (make-instance 'point))
(set-x b 6)
(set-y b 3)
(setf c (make-instance 'point))
(set-x c 2)
(set-y c 1)

(setf tr (make-instance 'triangle))
(set-triangle tr a b c)
(setf poly (to-polygon tr))
(setf pic (make-instance 'picture))
(set-types-pic pic (list 'triangle 'point 'polygon))
(set-items-pic pic (list a tr b poly))

